<?php

declare(strict_types=1);

namespace MeatinOS\Services;

use MeatinOS\Core\Database;
use PDO;
use Throwable;

final class ScheduledReportService
{
    public function __construct(private ?PDO $pdo = null)
    {
        $this->pdo ??= Database::connection();
    }

    /** @return array<string,string> */
    public static function queries(): array
    {
        return [
            'production'=>"SELECT pb.batch_number,pb.production_date,br.batch_number receiving_batch,pb.birds_input,pb.input_weight_kg,pb.output_weight_kg,pb.rejected_weight_kg,pb.yield_percent,pb.stage,pb.status FROM production_batches pb JOIN bird_receipts br ON br.id=pb.bird_receipt_id ORDER BY pb.production_date DESC",
            'production_wastage'=>"SELECT psm.measurement_number,pb.batch_number,psm.stage,psm.measured_at,psm.blood_loss_kg,psm.head_waste_kg,psm.defeathering_waste_kg,psm.evisceration_waste_kg,psm.peeled_skin_waste_kg,psm.condemned_weight_kg,psm.packaging_waste_kg,(psm.blood_loss_kg+psm.head_waste_kg+psm.defeathering_waste_kg+psm.evisceration_waste_kg+psm.peeled_skin_waste_kg+psm.condemned_weight_kg+psm.packaging_waste_kg) total_waste_kg FROM production_stage_measurements psm JOIN production_batches pb ON pb.id=psm.production_batch_id WHERE (psm.blood_loss_kg+psm.head_waste_kg+psm.defeathering_waste_kg+psm.evisceration_waste_kg+psm.peeled_skin_waste_kg+psm.condemned_weight_kg+psm.packaging_waste_kg)>0 ORDER BY psm.measured_at DESC",
            'damaged_bird_wastage'=>"SELECT pdb.damage_number,pb.batch_number,pdb.stage,pdb.damaged_bird_count,pdb.damaged_weight_kg,pdb.reason_category,pdb.reason_details,pdb.disposition,pdb.recorded_at,pdb.status FROM production_damaged_birds pdb JOIN production_batches pb ON pb.id=pdb.production_batch_id ORDER BY pdb.recorded_at DESC",
            'inventory'=>"SELECT il.lot_number,p.sku,p.name product,z.name storage_zone,il.quantity,il.available_quantity,p.unit,il.expiry_date,il.temperature_c,il.status FROM inventory_lots il JOIN products p ON p.id=il.product_id JOIN storage_zones z ON z.id=il.storage_zone_id ORDER BY il.received_date DESC",
            'sales'=>"SELECT so.order_number,c.name customer,e.full_name salesman,receiver.full_name received_by_staff,so.order_date,so.delivery_date,so.delivery_time,so.delivery_location,so.total_amount,so.payment_status,so.status FROM sales_orders so JOIN customers c ON c.id=so.customer_id LEFT JOIN employees e ON e.id=COALESCE(so.sales_person_id,c.assigned_salesman_id) LEFT JOIN employees receiver ON receiver.id=so.received_by_employee_id ORDER BY so.order_date DESC",
            'salesman'=>"SELECT e.employee_number,e.full_name salesman,COALESCE(os.orders,0) orders,COALESCE(ls.quantity,0) quantity,COALESCE(os.sales_value,0) sales_value,COALESCE(ls.average_item_price,0) average_item_price FROM employees e LEFT JOIN (SELECT COALESCE(so.sales_person_id,c.assigned_salesman_id) salesperson_id,COUNT(*) orders,SUM(so.total_amount) sales_value FROM sales_orders so JOIN customers c ON c.id=so.customer_id WHERE so.status<>'cancelled' GROUP BY COALESCE(so.sales_person_id,c.assigned_salesman_id)) os ON os.salesperson_id=e.id LEFT JOIN (SELECT COALESCE(so.sales_person_id,c.assigned_salesman_id) salesperson_id,SUM(soi.quantity) quantity,AVG(soi.unit_price) average_item_price FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.sales_order_id JOIN customers c ON c.id=so.customer_id WHERE so.status<>'cancelled' GROUP BY COALESCE(so.sales_person_id,c.assigned_salesman_id)) ls ON ls.salesperson_id=e.id WHERE e.department='Sales' ORDER BY sales_value DESC,e.full_name",
            'salesman_tracking'=>"SELECT s.tracking_number,e.employee_number,e.full_name salesman,c.name customer,r.name route,s.visit_purpose,s.location_name,s.started_at,s.ended_at,TIMESTAMPDIFF(MINUTE,s.started_at,COALESCE(s.ended_at,NOW())) duration_minutes,s.distance_km,s.last_latitude,s.last_longitude,s.last_ping_at,s.status FROM salesman_tracking_sessions s JOIN employees e ON e.id=s.employee_id LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN route_masters r ON r.id=s.route_master_id ORDER BY s.started_at DESC",
            'employee_daily_tasks'=>"SELECT t.task_number,t.task_date,e.employee_number,e.full_name,m.full_name manager,t.title,t.description,t.priority,t.due_at,t.status,t.completed_at,t.completion_notes FROM employee_tasks t JOIN employees e ON e.id=t.employee_id LEFT JOIN employees m ON m.id=t.manager_id ORDER BY t.task_date DESC,e.full_name,t.id",
            'employee_inactivity'=>"SELECT e.employee_number,e.full_name,e.department,e.job_title,eas.last_activity_at,eas.last_route,eas.last_location_ping_at,eas.last_reminder_at,eas.reminder_count FROM employees e LEFT JOIN employee_activity_status eas ON eas.employee_id=e.id WHERE e.status='active' ORDER BY eas.last_activity_at,e.full_name",
            'sales_received_person'=>"SELECT COALESCE(e.employee_number,'UNASSIGNED') employee_number,COALESCE(e.full_name,'Unassigned') received_by_staff,COUNT(*) orders,COALESCE(SUM(so.total_amount),0) sales_value,MIN(so.order_date) first_order_date,MAX(so.order_date) latest_order_date FROM sales_orders so LEFT JOIN employees e ON e.id=so.received_by_employee_id WHERE so.status<>'cancelled' GROUP BY so.received_by_employee_id,e.employee_number,e.full_name ORDER BY sales_value DESC,received_by_staff",
            'customer_ranking'=>"SELECT DENSE_RANK() OVER (ORDER BY COALESCE(os.total_sales,0) DESC) sales_rank,c.code,c.name,c.criticality,COALESCE(os.orders,0) orders,COALESCE(ls.item_quantity,0) item_quantity,COALESCE(ls.average_price,0) average_price,COALESCE(os.total_sales,0) total_sales,c.outstanding_balance,c.credit_limit FROM customers c LEFT JOIN (SELECT customer_id,COUNT(*) orders,SUM(total_amount) total_sales FROM sales_orders WHERE status<>'cancelled' GROUP BY customer_id) os ON os.customer_id=c.id LEFT JOIN (SELECT so.customer_id,SUM(soi.quantity) item_quantity,AVG(soi.unit_price) average_price FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.sales_order_id WHERE so.status<>'cancelled' GROUP BY so.customer_id) ls ON ls.customer_id=c.id ORDER BY total_sales DESC,c.name",
            'customer_comparison'=>"SELECT c.code,c.name,c.customer_type,c.criticality,COALESCE(os.orders,0) orders,COALESCE(ls.quantity,0) quantity,COALESCE(os.sales,0) sales,COALESCE(ls.average_price,0) average_price,c.credit_limit,c.outstanding_balance,COALESCE(inv.overdue,0) overdue FROM customers c LEFT JOIN (SELECT customer_id,COUNT(*) orders,SUM(total_amount) sales FROM sales_orders WHERE status<>'cancelled' GROUP BY customer_id) os ON os.customer_id=c.id LEFT JOIN (SELECT so.customer_id,SUM(soi.quantity) quantity,AVG(soi.unit_price) average_price FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.sales_order_id WHERE so.status<>'cancelled' GROUP BY so.customer_id) ls ON ls.customer_id=c.id LEFT JOIN (SELECT customer_id,SUM(CASE WHEN status='overdue' OR (status IN ('issued','partial') AND due_date<CURDATE()) THEN balance_amount ELSE 0 END) overdue FROM invoices GROUP BY customer_id) inv ON inv.customer_id=c.id ORDER BY sales DESC,c.name",
            'vendor_comparison'=>"SELECT s.code,s.name,s.supplier_type,s.approval_status,COALESCE(poa.purchase_orders,0) purchase_orders,COALESCE(poa.purchase_value,0) purchase_value,COALESCE(bra.bird_batches,0) bird_batches,COALESCE(bra.birds,0) birds,COALESCE(bra.mortality_percent,0) mortality_percent,COALESCE(bra.average_bird_cost,0) average_bird_cost,s.outstanding_balance FROM suppliers s LEFT JOIN (SELECT supplier_id,COUNT(*) purchase_orders,SUM(total_amount) purchase_value FROM purchase_orders WHERE status<>'cancelled' GROUP BY supplier_id) poa ON poa.supplier_id=s.id LEFT JOIN (SELECT supplier_id,COUNT(*) bird_batches,SUM(bird_count) birds,SUM(mortality_count)/NULLIF(SUM(bird_count),0)*100 mortality_percent,AVG(unit_purchase_cost) average_bird_cost FROM bird_receipts GROUP BY supplier_id) bra ON bra.supplier_id=s.id ORDER BY purchase_value DESC,s.name",
            'customer_ledger'=>"SELECT c.code,c.name,cmb.month_start,cmb.opening_balance,cmb.invoice_amount,cmb.payment_amount,cmb.credit_amount,cmb.closing_balance,cmb.generated_at FROM customer_monthly_balances cmb JOIN customers c ON c.id=cmb.customer_id ORDER BY cmb.month_start DESC,c.name",
            'price_comparison'=>"SELECT rc.rate_card_number,rc.name rate_card,p.sku,p.name product,rci.hsn_code,rci.calculated_price,rci.unit_price rate_card_price,mp.unit_price market_price,mp.price_date market_date,(rci.unit_price-mp.unit_price) variance,(rci.unit_price/NULLIF(mp.unit_price,0)-1)*100 variance_percent FROM rate_card_items rci JOIN rate_cards rc ON rc.id=rci.rate_card_id JOIN products p ON p.id=rci.product_id LEFT JOIN market_prices mp ON mp.id=(SELECT mp2.id FROM market_prices mp2 WHERE mp2.product_id=p.id ORDER BY mp2.price_date DESC,mp2.id DESC LIMIT 1) ORDER BY rc.name,p.name",
            'dispatch'=>"SELECT d.dispatch_number,so.order_number,c.name customer,v.registration_number,e.full_name driver,d.route_name,d.planned_departure,d.actual_departure,d.delivered_at,d.temperature_c load_temperature_c,d.delivery_temperature_c,d.delivery_temperature_recorded_at,d.status,d.pod_reference FROM dispatches d JOIN sales_orders so ON so.id=d.sales_order_id JOIN customers c ON c.id=so.customer_id JOIN vehicles v ON v.id=d.vehicle_id JOIN employees e ON e.id=d.driver_id ORDER BY d.planned_departure DESC",
            'attendance'=>"SELECT e.employee_number,e.full_name,e.department,a.attendance_date,a.check_in,a.check_out,a.regular_hours,a.overtime_hours,a.source,a.status FROM attendance a JOIN employees e ON e.id=a.employee_id ORDER BY a.attendance_date DESC,e.full_name",
            'payroll'=>"SELECT pr.run_number,pr.period_start,pr.period_end,pr.pay_date,e.employee_number,e.full_name,e.department,pi.basic_amount,pi.overtime_hours,pi.overtime_amount,pi.allowances,pi.deductions,pi.net_amount,pr.status FROM payroll_items pi JOIN payroll_runs pr ON pr.id=pi.payroll_run_id JOIN employees e ON e.id=pi.employee_id ORDER BY pr.period_end DESC,e.full_name",
            'maintenance'=>"SELECT mt.ticket_number,a.asset_code,a.name asset,mt.ticket_type,mt.priority,mt.reported_at,mt.scheduled_date,mt.downtime_minutes,mt.status,mt.resolution FROM maintenance_tickets mt JOIN assets a ON a.id=mt.asset_id ORDER BY mt.reported_at DESC",
            'quality'=>"SELECT qc.check_number,pb.batch_number production_batch,qc.checkpoint,qc.checked_at,qc.sample_size,qc.accepted_qty,qc.rejected_qty,qc.grade,qc.weight_kg,qc.temperature_c,qc.status,qc.corrective_action FROM quality_checks qc JOIN production_batches pb ON pb.id=qc.production_batch_id ORDER BY qc.checked_at DESC",
            'cold_storage'=>"SELECT z.code zone_code,z.name,z.zone_type,z.capacity_kg,z.current_temperature_c,z.status,COALESCE(SUM(l.available_quantity),0) used_kg,MIN(l.expiry_date) nearest_expiry FROM storage_zones z LEFT JOIN inventory_lots l ON l.storage_zone_id=z.id AND l.status IN ('available','allocated') GROUP BY z.id ORDER BY z.code",
            'profitability'=>"SELECT DATE_FORMAT(i.invoice_date,'%Y-%m') month,SUM(i.total_amount) revenue,SUM(i.balance_amount) outstanding FROM invoices i WHERE i.status<>'cancelled' GROUP BY DATE_FORMAT(i.invoice_date,'%Y-%m') ORDER BY month DESC",
            'bird_receiving'=>"SELECT br.batch_number,br.received_at,s.name supplier,br.farm_name,br.vehicle_number,br.bird_count,br.mortality_count,br.gross_weight_kg,br.tare_weight_kg,br.net_weight_kg,br.unit_purchase_cost,br.total_value,br.vet_status,br.status FROM bird_receipts br JOIN suppliers s ON s.id=br.supplier_id ORDER BY br.received_at DESC",
            'carcass'=>"SELECT pb.batch_number,pb.production_date,yr.carcass_quantity,yr.carcass_weight_kg,yr.by_product_weight_kg,yr.waste_weight_kg,yr.finished_weight_kg,yr.deboned_weight_kg,yr.carcass_yield_percent,yr.saleable_yield_percent,yr.waste_percent,yr.variance_percent FROM yield_records yr JOIN production_batches pb ON pb.id=yr.production_batch_id ORDER BY pb.production_date DESC",
            'carcass_allocation'=>"SELECT ca.allotment_number allocation_number,pb.batch_number,p.sku,p.name product,ca.grade,ca.destination,so.order_number,ca.quantity,ca.weight_kg,ca.allotted_at allocated_at FROM carcass_allotments ca JOIN production_batches pb ON pb.id=ca.production_batch_id LEFT JOIN products p ON p.id=ca.product_id LEFT JOIN sales_orders so ON so.id=ca.sales_order_id ORDER BY ca.allotted_at DESC",
            'item_sales'=>"SELECT p.sku,p.brand_name,p.name product,p.unit,COUNT(DISTINCT so.id) orders,SUM(soi.quantity) quantity,AVG(soi.unit_price) average_rate,SUM(soi.line_total) sales_value FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.sales_order_id JOIN products p ON p.id=soi.product_id WHERE so.status<>'cancelled' GROUP BY p.id ORDER BY sales_value DESC",
            'item_purchase'=>"SELECT p.sku,p.brand_name,p.name product,gri.unit,COUNT(DISTINCT gr.id) receipts,SUM(gri.quantity) quantity,AVG(gri.unit_cost) average_cost,SUM(gri.quantity*gri.unit_cost) purchase_value FROM goods_receipt_items gri JOIN goods_receipts gr ON gr.id=gri.goods_receipt_id JOIN products p ON p.id=gri.product_id WHERE gr.status='accepted' GROUP BY p.id,gri.unit ORDER BY purchase_value DESC",
            'party_sales'=>"SELECT c.code,c.name,c.customer_type,COALESCE(so.orders,0) orders,COALESCE(so.sales_value,0) sales_value,COALESCE(i.outstanding,0) outstanding FROM customers c LEFT JOIN (SELECT customer_id,COUNT(*) orders,SUM(total_amount) sales_value FROM sales_orders WHERE status<>'cancelled' GROUP BY customer_id) so ON so.customer_id=c.id LEFT JOIN (SELECT customer_id,SUM(balance_amount) outstanding FROM invoices WHERE status IN ('issued','partial','overdue') GROUP BY customer_id) i ON i.customer_id=c.id ORDER BY sales_value DESC",
            'party_purchase'=>"SELECT s.code,s.name,s.supplier_type,COALESCE(po.purchase_orders,0) purchase_orders,COALESCE(po.ordered_value,0) ordered_value,COALESCE(si.outstanding,0) outstanding FROM suppliers s LEFT JOIN (SELECT supplier_id,COUNT(*) purchase_orders,SUM(total_amount) ordered_value FROM purchase_orders WHERE status<>'cancelled' GROUP BY supplier_id) po ON po.supplier_id=s.id LEFT JOIN (SELECT supplier_id,SUM(balance_amount) outstanding FROM supplier_invoices WHERE status IN ('approved','partial','overdue') GROUP BY supplier_id) si ON si.supplier_id=s.id ORDER BY ordered_value DESC",
            'stock'=>"SELECT il.lot_number,p.sku,p.brand_name,p.name product,sz.name storage_zone,il.received_date,il.expiry_date,il.quantity,il.available_quantity,p.unit,il.unit_cost,il.available_quantity*il.unit_cost stock_value,DATEDIFF(CURDATE(),il.received_date) age_days,il.status FROM inventory_lots il JOIN products p ON p.id=il.product_id JOIN storage_zones sz ON sz.id=il.storage_zone_id ORDER BY il.received_date",
            'production_brand'=>"SELECT p.brand_name,p.sku,p.name product,pb.batch_number,pb.production_date,po.grade,po.quantity,po.unit_cost,po.quantity*po.unit_cost production_value,po.qc_status FROM production_outputs po JOIN production_batches pb ON pb.id=po.production_batch_id JOIN products p ON p.id=po.product_id ORDER BY pb.production_date DESC,p.brand_name,p.name",
            'order_confirmation'=>"SELECT so.order_number,so.order_date,so.delivery_date,so.delivery_time,c.name customer,e.full_name salesman,COUNT(soi.id) item_lines,SUM(soi.quantity) total_quantity,so.total_amount,so.status FROM sales_orders so JOIN customers c ON c.id=so.customer_id LEFT JOIN employees e ON e.id=COALESCE(so.sales_person_id,c.assigned_salesman_id) LEFT JOIN sales_order_items soi ON soi.sales_order_id=so.id GROUP BY so.id ORDER BY so.order_date DESC",
            'remaining_balance'=>"SELECT i.invoice_number,i.invoice_date,i.due_date,c.code customer_code,c.name customer,i.total_amount,i.paid_amount,i.balance_amount,DATEDIFF(CURDATE(),i.due_date) overdue_days,i.status FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.balance_amount>0 AND i.status<>'cancelled' ORDER BY i.due_date",
            'invoicing'=>"SELECT i.invoice_number,i.invoice_date,i.due_date,so.order_number,c.code customer_code,c.name customer,i.subtotal,i.tax_amount gst_amount,i.total_amount,i.paid_amount,i.balance_amount,i.status FROM invoices i JOIN customers c ON c.id=i.customer_id JOIN sales_orders so ON so.id=i.sales_order_id ORDER BY i.invoice_date DESC",
            'billing'=>"SELECT i.invoice_number,i.invoice_date,c.name customer,p.sku,p.name product,soi.quantity,soi.unit_price,soi.discount_amount,soi.tax_amount gst_amount,soi.line_total,i.status FROM invoices i JOIN sales_orders so ON so.id=i.sales_order_id JOIN sales_order_items soi ON soi.sales_order_id=so.id JOIN products p ON p.id=soi.product_id JOIN customers c ON c.id=i.customer_id ORDER BY i.invoice_date DESC,i.id,soi.id",
            'grading'=>"SELECT pb.batch_number,pb.production_date,po.grade,p.brand_name,p.name product,SUM(po.quantity) graded_quantity,AVG(po.unit_cost) unit_cost,po.qc_status FROM production_outputs po JOIN production_batches pb ON pb.id=po.production_batch_id JOIN products p ON p.id=po.product_id GROUP BY pb.id,po.grade,p.id,po.qc_status ORDER BY pb.production_date DESC,po.grade",
            'daily_attendance'=>"SELECT a.attendance_date,e.employee_number,e.full_name,e.department,e.job_title designation,a.check_in,a.check_out,a.regular_hours,a.overtime_hours,a.extra_duty_hours,a.duty_type,a.source,a.status FROM attendance a JOIN employees e ON e.id=a.employee_id ORDER BY a.attendance_date DESC,e.full_name",
            'sales_return'=>"SELECT sr.return_number,sr.return_date,so.order_number,i.invoice_number,c.code customer_code,c.name customer,sr.quantity_received,sr.reason,sr.credit_note_number,sr.credit_amount,sr.status FROM sales_returns sr JOIN customers c ON c.id=sr.customer_id LEFT JOIN sales_orders so ON so.id=sr.sales_order_id LEFT JOIN invoices i ON i.id=sr.invoice_id ORDER BY sr.return_date DESC",
            'order_conversion'=>"SELECT DATE_FORMAT(sq.quote_date,'%Y-%m') month,COUNT(*) quotations,SUM(sq.status='converted') converted,ROUND(SUM(sq.status='converted')/NULLIF(COUNT(*),0)*100,2) conversion_percent,SUM(sq.total_amount) quoted_value,SUM(CASE WHEN sq.status='converted' THEN sq.total_amount ELSE 0 END) converted_value FROM sales_quotations sq GROUP BY DATE_FORMAT(sq.quote_date,'%Y-%m') ORDER BY month DESC",
            'stock_age'=>"SELECT p.sku,p.name product,il.lot_number,il.received_date,il.expiry_date,il.available_quantity,p.unit,DATEDIFF(CURDATE(),il.received_date) age_days,CASE WHEN DATEDIFF(CURDATE(),il.received_date)>90 THEN 'dead_stock' WHEN DATEDIFF(CURDATE(),il.received_date)>30 THEN 'slow_moving' ELSE 'current' END age_band,il.available_quantity*il.unit_cost stock_value FROM inventory_lots il JOIN products p ON p.id=il.product_id WHERE il.available_quantity>0 ORDER BY age_days DESC",
            'accounting_daybook'=>"SELECT je.entry_date,je.entry_number,je.reference_type,je.reference_id,je.description,coa.account_code,coa.account_name,coa.account_type,jl.debit,jl.credit,je.status,je.posted_at FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id JOIN chart_of_accounts coa ON coa.id=jl.account_id ORDER BY je.entry_date DESC,je.id DESC,jl.id",
            'inventory_daybook'=>"SELECT sm.moved_at,il.lot_number,p.sku,p.name product,sm.movement_type,sm.quantity,fz.name from_zone,tz.name to_zone,sm.reference_type,sm.reference_id,sm.reason FROM stock_movements sm JOIN inventory_lots il ON il.id=sm.inventory_lot_id JOIN products p ON p.id=il.product_id LEFT JOIN storage_zones fz ON fz.id=sm.from_zone_id LEFT JOIN storage_zones tz ON tz.id=sm.to_zone_id ORDER BY sm.moved_at DESC,sm.id DESC",
            'gst'=>"SELECT entry_date,source_number,party,taxable_amount,input_gst,output_gst FROM (SELECT i.invoice_date entry_date,i.invoice_number source_number,c.name party,i.subtotal taxable_amount,0 input_gst,i.tax_amount output_gst FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.status<>'cancelled' UNION ALL SELECT si.invoice_date,si.invoice_number,s.name,si.subtotal,si.tax_amount,0 FROM supplier_invoices si JOIN suppliers s ON s.id=si.supplier_id WHERE si.status<>'cancelled' UNION ALL SELECT oe.expense_date,oe.expense_number,COALESCE(s.name,oe.description),oe.taxable_amount,oe.gst_amount,0 FROM operating_expenses oe LEFT JOIN suppliers s ON s.id=oe.supplier_id WHERE oe.status IN ('paid','reversed')) gst_book ORDER BY entry_date DESC",
            'cash_bank_balance'=>"SELECT cba.account_code,c.name company,cba.bank_name,cba.branch_name,cba.masked_account,cba.account_type,cba.opening_balance,cba.current_balance,cba.is_primary,cba.status FROM company_bank_accounts cba JOIN companies c ON c.id=cba.company_id ORDER BY cba.is_primary DESC,cba.bank_name",
            'billed_orders'=>"SELECT so.order_number,so.order_date,c.name customer,i.invoice_number,i.invoice_date,i.total_amount,i.paid_amount,i.balance_amount,i.status invoice_status,so.status order_status FROM sales_orders so JOIN customers c ON c.id=so.customer_id JOIN invoices i ON i.sales_order_id=so.id WHERE i.status<>'cancelled' ORDER BY i.invoice_date DESC",
            'customer_list'=>"SELECT c.code,c.name,c.customer_type,c.criticality,c.phone,c.email,c.address,c.tax_number,c.payment_terms_days,c.credit_limit,c.outstanding_balance,e.full_name assigned_salesman,c.status FROM customers c LEFT JOIN employees e ON e.id=c.assigned_salesman_id ORDER BY c.name",
            'order_history'=>"SELECT so.order_number,so.order_date,so.delivery_date,c.code customer_code,c.name customer,p.sku,p.name product,soi.quantity,soi.unit_price,soi.line_total,so.payment_status,so.status FROM sales_orders so JOIN customers c ON c.id=so.customer_id JOIN sales_order_items soi ON soi.sales_order_id=so.id JOIN products p ON p.id=soi.product_id ORDER BY so.order_date DESC,so.id,soi.id",
            'production_calendar'=>"SELECT ce.event_number,ce.title,ce.start_at,ce.end_at,ce.location,ce.related_type,ce.related_id,ce.status,ce.description FROM calendar_events ce WHERE ce.event_type='production' ORDER BY ce.start_at",
            'eway_bill'=>"SELECT eb.eway_bill_number,eb.document_date,i.invoice_number,d.dispatch_number,eb.transporter_name,eb.transporter_gstin,eb.vehicle_number,eb.distance_km,eb.valid_until,eb.status FROM eway_bills eb LEFT JOIN invoices i ON i.id=eb.invoice_id LEFT JOIN dispatches d ON d.id=eb.dispatch_id ORDER BY eb.document_date DESC",
            'creditor_ledger'=>"SELECT entry_date,supplier_code,supplier,reference_number,entry_type,debit,credit FROM (SELECT si.invoice_date entry_date,s.code supplier_code,s.name supplier,si.invoice_number reference_number,'invoice' entry_type,0 debit,si.total_amount credit FROM supplier_invoices si JOIN suppliers s ON s.id=si.supplier_id WHERE si.status<>'cancelled' UNION ALL SELECT sp.payment_date,s.code,s.name,sp.payment_number,'payment',sp.amount,0 FROM supplier_payments sp JOIN suppliers s ON s.id=sp.supplier_id WHERE sp.status='cleared') ledger ORDER BY entry_date DESC,supplier",
            'daily_payments'=>"SELECT payment_date,payment_number,party,payment_direction,amount,payment_method,reference_number,status FROM (SELECT p.payment_date,p.payment_number,c.name party,'received' payment_direction,p.amount,p.payment_method,p.reference_number,p.status FROM payments p JOIN customers c ON c.id=p.customer_id UNION ALL SELECT sp.payment_date,sp.payment_number,s.name,'paid',sp.amount,sp.payment_method,sp.reference_number,sp.status FROM supplier_payments sp JOIN suppliers s ON s.id=sp.supplier_id) payments_book ORDER BY payment_date DESC",
            'pending_received_payments'=>"SELECT i.invoice_number,i.due_date,c.name customer,i.total_amount,i.paid_amount,i.balance_amount,i.status,'receivable' balance_type FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.balance_amount>0 AND i.status<>'cancelled' UNION ALL SELECT si.invoice_number,si.due_date,s.name,si.total_amount,si.paid_amount,si.balance_amount,si.status,'payable' FROM supplier_invoices si JOIN suppliers s ON s.id=si.supplier_id WHERE si.balance_amount>0 AND si.status<>'cancelled' ORDER BY due_date",
            'costing'=>"SELECT pb.batch_number,pb.production_date,pbc.cost_component,cc.center_code cost_center,pbc.description,pbc.quantity,pbc.unit_rate,pbc.amount,pbc.status FROM production_batch_costs pbc JOIN production_batches pb ON pb.id=pbc.production_batch_id LEFT JOIN cost_centers cc ON cc.id=pbc.cost_center_id ORDER BY pb.production_date DESC,pbc.id",
            'growth_analysis'=>"SELECT DATE_FORMAT(i.invoice_date,'%Y-%m') month,SUM(i.total_amount) revenue,LAG(SUM(i.total_amount)) OVER (ORDER BY DATE_FORMAT(i.invoice_date,'%Y-%m')) previous_revenue,ROUND((SUM(i.total_amount)-LAG(SUM(i.total_amount)) OVER (ORDER BY DATE_FORMAT(i.invoice_date,'%Y-%m')))/NULLIF(LAG(SUM(i.total_amount)) OVER (ORDER BY DATE_FORMAT(i.invoice_date,'%Y-%m')),0)*100,2) growth_percent FROM invoices i WHERE i.status<>'cancelled' GROUP BY DATE_FORMAT(i.invoice_date,'%Y-%m') ORDER BY month DESC",
            'fixed_assets'=>"SELECT a.asset_code,a.name,a.category asset_type,a.location,a.acquisition_date,a.acquisition_cost,a.residual_value,a.useful_life_months,a.accumulated_depreciation,a.acquisition_cost-a.accumulated_depreciation book_value,cc.center_code cost_center,a.status FROM assets a LEFT JOIN cost_centers cc ON cc.id=a.cost_center_id ORDER BY a.asset_code",
            'cost_center'=>"SELECT cc.center_code,cc.name,cc.budget_amount,COALESCE((SELECT SUM(oe.total_amount) FROM operating_expenses oe WHERE oe.cost_center_id=cc.id AND oe.status='paid'),0) operating_expenses,COALESCE((SELECT SUM(pbc.amount) FROM production_batch_costs pbc WHERE pbc.cost_center_id=cc.id AND pbc.status='actual'),0) production_cost,cc.status FROM cost_centers cc ORDER BY cc.center_code",
            'commission'=>"SELECT st.target_code,e.employee_number,e.full_name,st.period_start,st.period_end,st.target_amount,st.achieved_amount,st.commission_rate,st.commission_amount,sca.status,pr.run_number payroll_run FROM sales_targets st JOIN employees e ON e.id=st.employee_id LEFT JOIN sales_commission_accruals sca ON sca.target_id=st.id LEFT JOIN payroll_runs pr ON pr.id=sca.payroll_run_id ORDER BY st.period_end DESC,e.full_name",
            'employee_staff'=>"SELECT e.employee_number,e.full_name,e.department,e.job_title designation,e.phone,e.email,e.date_of_birth,e.join_date,e.employment_status,e.uan_number,e.esi_number,e.insurance_number,e.emergency_contact,e.status FROM employees e ORDER BY e.department,e.full_name",
            'batch_profitability'=>"SELECT pb.batch_number,pb.production_date,pb.input_weight_kg,pb.output_weight_kg,pb.yield_percent,COALESCE((SELECT SUM(amount) FROM production_batch_costs WHERE production_batch_id=pb.id AND status='actual'),0) total_cost,COALESCE((SELECT SUM(quantity*unit_cost) FROM production_outputs WHERE production_batch_id=pb.id AND qc_status='released'),0) production_value,COALESCE((SELECT SUM(quantity*unit_cost) FROM production_outputs WHERE production_batch_id=pb.id AND qc_status='released'),0)-COALESCE((SELECT SUM(amount) FROM production_batch_costs WHERE production_batch_id=pb.id AND status='actual'),0) batch_margin FROM production_batches pb ORDER BY pb.production_date DESC",
            'general_ledger'=>"SELECT coa.account_code,coa.account_name,coa.account_type,je.entry_date,je.entry_number,je.reference_type,je.reference_id,jl.description,jl.debit,jl.credit,SUM(jl.debit-jl.credit) OVER (PARTITION BY coa.id ORDER BY je.entry_date,je.id,jl.id) running_balance FROM journal_lines jl JOIN journal_entries je ON je.id=jl.journal_entry_id JOIN chart_of_accounts coa ON coa.id=jl.account_id WHERE je.status='posted' ORDER BY coa.account_code,je.entry_date,je.id,jl.id",
            'profit_loss'=>"SELECT coa.account_type,coa.account_code,coa.account_name,SUM(jl.debit) debit,SUM(jl.credit) credit,CASE WHEN coa.account_type='revenue' THEN SUM(jl.credit-jl.debit) ELSE SUM(jl.debit-jl.credit) END net_amount FROM chart_of_accounts coa JOIN journal_lines jl ON jl.account_id=coa.id JOIN journal_entries je ON je.id=jl.journal_entry_id WHERE je.status='posted' AND coa.account_type IN ('revenue','expense') GROUP BY coa.id ORDER BY coa.account_type DESC,coa.account_code",
            'vehicle_gate'=>"SELECT vgl.gate_log_number,vgl.registration_number,vgl.driver_name,vgl.purpose,vgl.entry_at,vgl.exit_at,vgl.odometer_in,vgl.odometer_out,vgl.related_type,vgl.related_id,vgl.status FROM vehicle_gate_logs vgl ORDER BY vgl.entry_at DESC",
            'partner_ledger'=>"SELECT pt.transaction_date,pt.transaction_number,sh.shareholder_code partner_id,sh.name partner,pt.transaction_type,pt.share_quantity,pt.amount,pt.payment_method,pt.reference_number,pt.status FROM partner_transactions pt JOIN shareholders sh ON sh.id=pt.shareholder_id ORDER BY pt.transaction_date DESC,pt.id DESC",
            'dead_stock'=>"SELECT p.sku,p.name product,il.lot_number,il.received_date,il.expiry_date,il.available_quantity,p.unit,il.unit_cost,il.available_quantity*il.unit_cost stock_value,DATEDIFF(CURDATE(),il.received_date) age_days FROM inventory_lots il JOIN products p ON p.id=il.product_id WHERE il.available_quantity>0 AND il.received_date<CURDATE()-INTERVAL 90 DAY AND NOT EXISTS (SELECT 1 FROM sales_order_items soi JOIN sales_orders so ON so.id=soi.sales_order_id WHERE soi.inventory_lot_id=il.id AND so.order_date>=CURDATE()-INTERVAL 90 DAY AND so.status<>'cancelled') ORDER BY age_days DESC",
        ];
    }

    /** @return array<string,string> */
    public static function labels(): array
    {
        return [
            'production'=>'Production, Yield & Mortality','production_wastage'=>'Production Wastage','damaged_bird_wastage'=>'Damaged Bird Wastage','bird_receiving'=>'Bird Receiving','carcass'=>'Carcass & Yield','carcass_allocation'=>'Carcass Allocation','production_brand'=>'Brand-wise Production','grading'=>'Grading','batch_profitability'=>'Batch Profitability','costing'=>'Production Costing','production_calendar'=>'Production Calendar',
            'inventory'=>'Inventory & Expiry','stock'=>'Stock Register','stock_age'=>'Stock Ageing','inventory_daybook'=>'Inventory Daybook','dead_stock'=>'Dead Stock','cold_storage'=>'Cold Storage',
            'sales'=>'Sales & Orders','salesman'=>'Salesman-wise Sales','salesman_tracking'=>'Salesman Location & Visit Tracking','sales_received_person'=>'Sales by Receiving Staff','item_sales'=>'Item-wise Sales','party_sales'=>'Party-wise Sales','order_confirmation'=>'Order Confirmation','order_history'=>'Order History','order_conversion'=>'Quotation Conversion','billed_orders'=>'Billed Orders','billing'=>'Item Billing','invoicing'=>'Invoice Register','sales_return'=>'Sales Returns','remaining_balance'=>'Remaining Customer Balances','customer_list'=>'Customer List','customer_ranking'=>'Customer Ranking','customer_comparison'=>'Customer Comparison','customer_ledger'=>'Customer Ledger','price_comparison'=>'Market Price Comparison',
            'item_purchase'=>'Item-wise Purchase','party_purchase'=>'Party-wise Purchase','vendor_comparison'=>'Vendor Comparison','creditor_ledger'=>'Creditor Ledger',
            'dispatch'=>'Dispatch & POD','eway_bill'=>'E-Way Bills','vehicle_gate'=>'Vehicle Entry / Exit',
            'attendance'=>'Attendance & Overtime','daily_attendance'=>'Daily Attendance','employee_daily_tasks'=>'Daily Employee Tasks','employee_inactivity'=>'Office-hours Inactivity','payroll'=>'Payroll Register','employee_staff'=>'Employee / Staff Register','commission'=>'Sales Commission',
            'accounting_daybook'=>'Accounting Daybook','general_ledger'=>'General Ledger','profit_loss'=>'Profit & Loss','gst'=>'GST Register','cash_bank_balance'=>'Cash & Bank Balances','daily_payments'=>'Day-by-day Payments','pending_received_payments'=>'Pending / Received Payments','fixed_assets'=>'Fixed Assets','cost_center'=>'Cost Centers','growth_analysis'=>'Growth Analysis','profitability'=>'Profitability','partner_ledger'=>'Partner Ledger',
            'quality'=>'Quality & Rejections','maintenance'=>'Maintenance & Downtime',
        ];
    }

    public function rows(string $type): array
    {
        $queries = self::queries();
        if (!isset($queries[$type])) throw new \RuntimeException('Report type is not supported.', 404);
        return $this->pdo->query($queries[$type])->fetchAll();
    }

    public function refreshMonthlyBalances(): void
    {
        $month = date('Y-m-01');
        $statement = $this->pdo->prepare("INSERT INTO customer_monthly_balances (customer_id,month_start,opening_balance,invoice_amount,payment_amount,credit_amount,closing_balance,generated_at) SELECT c.id,?,COALESCE((SELECT SUM(i.total_amount) FROM invoices i WHERE i.customer_id=c.id AND i.status<>'cancelled' AND i.invoice_date<?),0)-COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.status='cleared' AND p.payment_date<?),0)-COALESCE((SELECT SUM(sr.credit_amount) FROM sales_returns sr WHERE sr.customer_id=c.id AND sr.status IN ('credited','closed') AND sr.return_date<?),0),COALESCE((SELECT SUM(i.total_amount) FROM invoices i WHERE i.customer_id=c.id AND i.status<>'cancelled' AND i.invoice_date>=? AND i.invoice_date<? + INTERVAL 1 MONTH),0),COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.customer_id=c.id AND p.status='cleared' AND p.payment_date>=? AND p.payment_date<? + INTERVAL 1 MONTH),0),COALESCE((SELECT SUM(sr.credit_amount) FROM sales_returns sr WHERE sr.customer_id=c.id AND sr.status IN ('credited','closed') AND sr.return_date>=? AND sr.return_date<? + INTERVAL 1 MONTH),0),0,NOW() FROM customers c ON DUPLICATE KEY UPDATE opening_balance=VALUES(opening_balance),invoice_amount=VALUES(invoice_amount),payment_amount=VALUES(payment_amount),credit_amount=VALUES(credit_amount),closing_balance=VALUES(opening_balance)+VALUES(invoice_amount)-VALUES(payment_amount)-VALUES(credit_amount),generated_at=NOW()");
        $statement->execute([$month,$month,$month,$month,$month,$month,$month,$month,$month,$month]);
        $this->pdo->prepare('UPDATE customer_monthly_balances SET closing_balance=opening_balance+invoice_amount-payment_amount-credit_amount WHERE month_start=?')->execute([$month]);
    }

    public function generateDue(): int
    {
        $generated = 0;
        foreach ($this->pdo->query("SELECT * FROM report_schedules WHERE status='active' AND next_run_at<=NOW() ORDER BY next_run_at FOR UPDATE")->fetchAll() as $schedule) {
            $this->pdo->prepare("INSERT INTO report_runs (report_schedule_id,started_at,status) VALUES (?,NOW(),'running')")->execute([$schedule['id']]);
            $runId = (int) $this->pdo->lastInsertId();
            try {
                $rows = $this->rows((string) $schedule['report_type']);
                $directory = BASE_PATH . '/storage/reports/' . date('Y/m');
                if (!is_dir($directory) && !mkdir($directory,0750,true) && !is_dir($directory)) throw new \RuntimeException('Unable to create report storage.');
                $filename = preg_replace('/[^A-Za-z0-9_-]/','_',strtolower((string)$schedule['schedule_number'])) . '-' . date('Ymd-His') . '.csv';
                $absolute = $directory . '/' . $filename;
                $handle = fopen($absolute,'wb');
                if (!$handle) throw new \RuntimeException('Unable to create scheduled report file.');
                fwrite($handle,"\xEF\xBB\xBF");
                if ($rows) {
                    fputcsv($handle,array_keys($rows[0]));
                    foreach ($rows as $row) fputcsv($handle,$row);
                }
                fclose($handle); @chmod($absolute,0640);
                $relative = str_replace('\\','/',substr($absolute,strlen(BASE_PATH)+1));
                $this->pdo->prepare("UPDATE report_runs SET completed_at=NOW(),row_count=?,file_path=?,status='completed' WHERE id=?")->execute([count($rows),$relative,$runId]);
                $interval = match($schedule['frequency']) {'daily'=>'+1 day','weekly'=>'+1 week','monthly'=>'+1 month'};
                $next = date('Y-m-d H:i:s',strtotime($interval,strtotime((string)$schedule['next_run_at'])));
                while (strtotime($next) <= time()) $next = date('Y-m-d H:i:s',strtotime($interval,strtotime($next)));
                $this->pdo->prepare('UPDATE report_schedules SET next_run_at=? WHERE id=?')->execute([$next,$schedule['id']]);
                $generated++;
            } catch (Throwable $exception) {
                $this->pdo->prepare("UPDATE report_runs SET completed_at=NOW(),status='failed',error_message=? WHERE id=?")->execute([mb_substr($exception->getMessage(),0,1000),$runId]);
                $this->pdo->prepare('UPDATE report_schedules SET next_run_at=DATE_ADD(NOW(),INTERVAL 15 MINUTE) WHERE id=?')->execute([$schedule['id']]);
            }
        }
        return $generated;
    }
}
