<?php use MeatinOS\Core\Csrf; ?>
<div class="module-toolbar card-panel"><div><p class="eyebrow">Sales & CRM</p><h2>Salesman Live Tracking</h2><p>Consent-based field check-ins record visit time, route, customer, distance, and GPS history.</p></div><span class="badge text-bg-success"><?= e(count(array_filter($team,static fn(array $row):bool=>($row['status']??'')==='active'))) ?> active now</span></div>

<?php if ($isSalesperson && !$active): ?>
<section class="card-panel mb-4"><div class="panel-heading"><div><p class="eyebrow">Field employee check-in</p><h3>Start customer visit</h3></div><i class="bi bi-geo-alt-fill"></i></div>
<form action="<?= e(url('sales.tracking.start')) ?>" method="post" class="row g-3" data-location-form novalidate data-prevent-double-submit><?= Csrf::field() ?>
<div class="col-md-4"><label class="form-label" for="tracking_customer">Customer</label><select class="form-select" id="tracking_customer" name="customer_id"><option value="">Unplanned / prospect visit</option><?php foreach($customers as $customer): ?><option value="<?= e($customer['id']) ?>"><?= e($customer['code'].' · '.$customer['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="tracking_route">Planned route</label><select class="form-select" id="tracking_route" name="route_master_id"><option value="">No route selected</option><?php foreach($routes as $route): ?><option value="<?= e($route['id']) ?>"><?= e($route['route_code'].' · '.$route['name']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="tracking_location">Location name *</label><input class="form-control" id="tracking_location" name="location_name" maxlength="200" required></div>
<div class="col-md-6"><label class="form-label" for="tracking_purpose">Visit purpose *</label><input class="form-control" id="tracking_purpose" name="visit_purpose" maxlength="180" required></div><div class="col-md-6"><label class="form-label" for="tracking_notes">Notes</label><input class="form-control" id="tracking_notes" name="notes" maxlength="1500"></div>
<input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="accuracy_meters">
<div class="col-12 d-flex justify-content-end align-items-center gap-3"><span class="text-muted" data-location-status>Location has not been captured.</span><button class="btn btn-outline-primary" type="button" data-capture-location><i class="bi bi-crosshair me-1"></i>Capture location</button><button class="btn btn-danger" type="submit">Start tracking</button></div></form></section>
<?php elseif ($isSalesperson && $active): ?>
<section class="card-panel mb-4 active-tracking" data-sales-tracker data-ping-url="<?= e(url('sales.tracking.ping')) ?>" data-token="<?= e(MeatinOS\Core\Csrf::token()) ?>" data-ping-seconds="60"><div class="panel-heading"><div><p class="eyebrow">Live visit</p><h3><?= e($active['tracking_number'].' · '.$active['location_name']) ?></h3><p>Started <?= e(date('j M Y, g:i A',strtotime($active['started_at']))) ?></p></div><span class="live-dot">Live</span></div><p data-tracking-status>Waiting for the next secure location ping…</p><p><strong>Distance:</strong> <?= e(number_format((float)$active['distance_km'],3)) ?> km</p>
<form action="<?= e(url('sales.tracking.stop')) ?>" method="post" data-location-form novalidate data-prevent-double-submit><?= Csrf::field() ?><input type="hidden" name="latitude"><input type="hidden" name="longitude"><input type="hidden" name="accuracy_meters"><div class="d-flex justify-content-end align-items-center gap-3"><span class="text-muted" data-location-status>Capture the final location to finish.</span><button class="btn btn-outline-primary" type="button" data-capture-location>Capture final location</button><button class="btn btn-danger" type="submit">Complete visit</button></div></form></section>
<?php endif; ?>

<section class="card-panel table-panel mb-4"><div class="panel-heading"><div><p class="eyebrow">Current visibility</p><h3>Sales team status</h3></div></div><div class="table-responsive"><table class="table data-table align-middle"><thead><tr><th>Salesperson</th><th>Visit</th><th>Started</th><th>Last GPS ping</th><th>Distance</th><th>Status</th><th>Map</th></tr></thead><tbody><?php foreach($team as $member): ?><tr><td><strong><?= e($member['employee_number'].' · '.$member['full_name']) ?></strong></td><td><?= e(($member['customer_name']?:$member['location_name']) ?: 'No visit recorded') ?><small class="d-block text-muted"><?= e($member['route_name'] ?: '') ?></small></td><td><?= e($member['started_at']?date('j M, g:i A',strtotime($member['started_at'])):'—') ?></td><td><?= e($member['last_ping_at']?date('j M, g:i A',strtotime($member['last_ping_at'])):'—') ?></td><td><?= e(number_format((float)($member['distance_km']??0),3)) ?> km</td><td><span class="badge text-bg-<?= e(($member['status']??'')==='active'?'success':'secondary') ?>"><?= e(human_status($member['status']??'not checked in')) ?></span></td><td><?php if($member['last_latitude']!==null): ?><a class="btn btn-sm btn-light border" target="_blank" rel="noopener" href="https://www.google.com/maps?q=<?= e($member['last_latitude'].','.$member['last_longitude']) ?>"><i class="bi bi-map"></i></a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="card-panel table-panel"><div class="panel-heading"><div><p class="eyebrow">Audit history</p><h3>Recent field visits</h3></div><span><?= e(count($history)) ?> visits</span></div><div class="table-responsive"><table class="table data-table align-middle"><thead><tr><th>Tracking</th><th>Salesperson</th><th>Customer / location</th><th>Purpose</th><th>Start</th><th>Duration</th><th>Distance</th><th>Status</th></tr></thead><tbody><?php if(!$history): ?><tr><td colspan="8"><div class="table-empty"><i class="bi bi-geo"></i><strong>No field visits recorded</strong></div></td></tr><?php endif; ?><?php foreach($history as $visit): ?><tr><td><strong><?= e($visit['tracking_number']) ?></strong></td><td><?= e($visit['full_name']) ?></td><td><?= e($visit['customer_name']?:$visit['location_name']) ?><small class="d-block text-muted"><?= e($visit['route_name']?:'') ?></small></td><td><?= e($visit['visit_purpose']) ?></td><td><?= e(date('j M Y, g:i A',strtotime($visit['started_at']))) ?></td><td><?= e((int)$visit['duration_minutes']) ?> min</td><td><?= e(number_format((float)$visit['distance_km'],3)) ?> km</td><td><?= e(human_status($visit['status'])) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
