<?php use MeatinOS\Core\Csrf; ?>
<div class="module-toolbar card-panel">
    <div><p class="eyebrow">Identity & access</p><h2>Users & Role Permissions</h2><p>Least-privilege access mapped to Meatin's operating structure.</p></div>
    <?php if ($canManage): ?><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#userModal"><i class="bi bi-person-plus me-1"></i>Add user</button><?php endif; ?>
</div>
<div class="card-panel table-panel"><div class="table-responsive"><table class="table data-table align-middle"><thead><tr><th>User</th><th>Role</th><th>Linked profile</th><th>Status</th><th>Last login</th><th>Security</th><th></th></tr></thead><tbody>
<?php foreach ($users as $row): ?><tr><td><div class="record-primary"><span class="avatar avatar-sm"><?= e(mb_strtoupper(mb_substr((string) $row['name'],0,1))) ?></span><span><strong><?= e($row['name']) ?></strong><small class="d-block text-secondary"><?= e($row['email']) ?></small></span></div></td><td><strong><?= e($row['role_name']) ?></strong><small class="d-block text-secondary"><?= e($row['role_names'] ?: $row['role_name']) ?></small></td><td><?= e($row['employee_name'] ?: ($row['customer_name'] ?: 'System account')) ?></td><td><span class="badge rounded-pill text-bg-<?= e(status_class((string) $row['status'])) ?>"><?= e(human_status((string) $row['status'])) ?></span></td><td><?= $row['last_login_at'] ? e(date('j M Y, g:i A', strtotime((string) $row['last_login_at']))) : 'Never' ?></td><td><?= $row['must_change_password'] ? '<span class="badge text-bg-warning">Password change required</span>' : '<span class="badge text-bg-success">Current</span>' ?></td><td class="text-end"><?php if ($canManage): ?><a class="btn btn-sm btn-light border" href="<?= e(url('users',['edit'=>$row['id']])) ?>"><i class="bi bi-pencil"></i></a><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div>

<?php if ($canManage): ?>
<div class="modal fade" id="userModal" tabindex="-1" aria-hidden="true" data-auto-open="<?= $edit ? 'true' : 'false' ?>"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" method="post" action="<?= e(url('users.save')) ?>"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= e($edit['id'] ?? 0) ?>"><div class="modal-header"><div><p class="eyebrow mb-1"><?= $edit ? 'Update access' : 'New account' ?></p><h2 class="modal-title fs-4"><?= $edit ? 'Edit user' : 'Add user' ?></h2></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
    <div class="col-md-6"><label class="form-label">Full name *</label><input class="form-control" name="name" value="<?= e($edit['name'] ?? '') ?>" required></div>
    <div class="col-md-6"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" value="<?= e($edit['email'] ?? '') ?>" required></div>
    <div class="col-md-6"><label class="form-label">Primary role *</label><select class="form-select" name="role_id" required><option value="">Select...</option><?php foreach($roles as $role): ?><option value="<?= e($role['id']) ?>" <?= (string)($edit['role_id'] ?? '') === (string)$role['id'] ? 'selected' : '' ?>><?= e($role['name']) ?></option><?php endforeach; ?></select><div class="form-text">The primary role selects the user's portal and dashboard.</div></div>
    <div class="col-md-6"><label class="form-label">Status *</label><select class="form-select" name="status"><option value="active" <?= ($edit['status'] ?? 'active') === 'active' ? 'selected' : '' ?>>Active</option><option value="inactive" <?= ($edit['status'] ?? '') === 'inactive' ? 'selected' : '' ?>>Inactive</option><option value="locked" <?= ($edit['status'] ?? '') === 'locked' ? 'selected' : '' ?>>Locked</option></select></div>
    <div class="col-md-6"><label class="form-label">Employee profile</label><select class="form-select" name="employee_id"><option value="">None</option><?php foreach($employees as $employee): ?><option value="<?= e($employee['id']) ?>" <?= (string)($edit['employee_id'] ?? '') === (string)$employee['id'] ? 'selected' : '' ?>><?= e($employee['full_name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label">Customer profile</label><select class="form-select" name="customer_id"><option value="">None</option><?php foreach($customers as $customer): ?><option value="<?= e($customer['id']) ?>" <?= (string)($edit['customer_id'] ?? '') === (string)$customer['id'] ? 'selected' : '' ?>><?= e($customer['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-12"><label class="form-label">Assigned roles *</label><select class="form-select" name="role_ids[]" multiple size="8" required><?php $assignedRoles = $edit['role_ids'] ?? [($edit['role_id'] ?? '')]; foreach($roles as $role): ?><option value="<?= e($role['id']) ?>" <?= in_array((int) $role['id'], array_map('intval', $assignedRoles), true) ? 'selected' : '' ?>><?= e($role['name']) ?></option><?php endforeach; ?></select><div class="form-text">Use Ctrl/Cmd to select multiple roles. Permissions from all assigned roles are combined; explicit user denies still take precedence.</div></div>
    <div class="col-12"><label class="form-label"><?= $edit ? 'New password (leave blank to keep current)' : 'Temporary password *' ?></label><input class="form-control" type="password" name="password" autocomplete="new-password" <?= $edit ? '' : 'required' ?>><div class="form-text">At least 12 characters with upper-case, lower-case, number, and symbol. New users must change it at first sign-in.</div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button class="btn btn-danger" type="submit">Save access</button></div></form></div></div>
<?php endif; ?>
