<?php use MeatinOS\Core\Csrf; ?>
<div class="ai-hero card-panel">
    <div class="ai-hero-copy"><span class="ai-orb ai-orb-lg"><i class="bi bi-stars"></i></span><div><p class="eyebrow">Role-aware decision support</p><h2>Meatin AI</h2><p>Ask questions against live, permission-filtered ERP summaries. Every response is advisory and audited.</p></div></div>
    <div class="ai-state"><span class="status-pill <?= $aiSettings['enabled'] && $aiSettings['configured'] ? 'success' : 'secondary' ?>"><i class="bi bi-circle-fill"></i><?= $aiSettings['enabled'] && $aiSettings['configured'] ? 'OpenAI enabled' : 'OpenAI not configured' ?></span><?php if ($canConfigure): ?><a class="btn btn-sm btn-outline-secondary" href="<?= e(url('settings')) ?>#ai-settings"><i class="bi bi-sliders me-1"></i>Configure</a><?php endif; ?></div>
</div>

<?php if (!$aiSettings['enabled'] || !$aiSettings['configured']): ?><div class="alert alert-warning ai-notice"><i class="bi bi-key me-2"></i><strong>AI conversations are disabled.</strong> Rule-based operational insights remain available below. An administrator can securely add an API key in System Settings; no key is bundled with MeatinOS.</div><?php endif; ?>

<div class="ai-layout">
    <aside class="card-panel ai-sidebar">
        <div class="panel-heading"><div><h2>Assistants</h2><p>Only authorized modules appear</p></div></div>
        <div class="ai-assistant-list"><?php foreach ($assistants as $key=>$definition): ?><a class="<?= $assistant===$key?'active':'' ?>" href="<?= e(url('ai',['assistant'=>$key])) ?>"><i class="bi <?= e($definition[2]) ?>"></i><span><?= e($definition[0]) ?></span></a><?php endforeach; ?></div>
        <div class="ai-history-title"><span>Recent conversations</span><a href="<?= e(url('ai',['assistant'=>$assistant])) ?>" title="New conversation"><i class="bi bi-plus-lg"></i></a></div>
        <div class="ai-history"><?php if (!$conversations): ?><small>No conversations yet.</small><?php endif; ?><?php foreach ($conversations as $conversation): ?><a class="<?= (int)$conversation['id']===$conversationId?'active':'' ?>" href="<?= e(url('ai',['assistant'=>$conversation['assistant_type'],'conversation'=>$conversation['id']])) ?>"><i class="bi bi-chat-left-text"></i><span><strong><?= e($conversation['title']) ?></strong><small><?= e(date('d M, H:i',strtotime($conversation['updated_at']))) ?></small></span></a><?php endforeach; ?></div>
    </aside>

    <section class="card-panel ai-chat-panel">
        <div class="ai-chat-head"><div><span class="ai-orb"><i class="bi <?= e($assistants[$assistant][2] ?? 'bi-stars') ?>"></i></span><span><strong><?= e($assistants[$assistant][0] ?? 'Meatin AI') ?></strong><small>Authorized ERP snapshot · INR · advisory only</small></span></div><span class="badge rounded-pill text-bg-light">Model: <?= e($aiSettings['model'] ?? 'gpt-5.6') ?></span></div>
        <div class="ai-messages">
            <?php if (!$messages): ?><div class="ai-welcome"><span class="ai-orb ai-orb-lg"><i class="bi bi-stars"></i></span><h3>What should we investigate?</h3><p>Try a concise operational question. Meatin AI only receives summaries from modules your role can access.</p><div class="ai-prompts"><button type="button" data-ai-prompt="What are today's highest operational risks and the recommended review order?">Today's risks</button><button type="button" data-ai-prompt="Which exceptions need management attention and why?">Management exceptions</button><button type="button" data-ai-prompt="Summarize trends, evidence gaps, and safe next actions.">Trend summary</button></div></div><?php endif; ?>
            <?php foreach ($messages as $message): ?><article class="ai-message <?= e($message['role']) ?>"><span class="ai-message-avatar"><i class="bi <?= $message['role']==='assistant'?'bi-stars':'bi-person' ?>"></i></span><div><div class="ai-message-meta"><strong><?= $message['role']==='assistant'?'Meatin AI':e(MeatinOS\Core\Auth::user()['name']) ?></strong><small><?= e(date('d M Y, H:i',strtotime($message['created_at']))) ?><?= $message['model']?' · '.e($message['model']):'' ?></small></div><div class="ai-message-content"><?= nl2br(e($message['content'])) ?></div><?php if ($message['role']==='assistant' && $message['status']==='completed'): ?><div class="ai-feedback"><span>Was this useful?</span><form method="post" action="<?= e(url('ai.feedback')) ?>"><?= Csrf::field() ?><input type="hidden" name="message_id" value="<?= e($message['id']) ?>"><input type="hidden" name="conversation_id" value="<?= e($conversationId) ?>"><input type="hidden" name="assistant" value="<?= e($assistant) ?>"><button name="rating" value="helpful" title="Helpful"><i class="bi bi-hand-thumbs-up"></i></button><button name="rating" value="unhelpful" title="Not helpful"><i class="bi bi-hand-thumbs-down"></i></button></form></div><?php endif; ?></div></article><?php endforeach; ?>
        </div>
        <form class="ai-composer" method="post" action="<?= e(url('ai.ask')) ?>"><?= Csrf::field() ?><input type="hidden" name="assistant" value="<?= e($assistant) ?>"><input type="hidden" name="conversation_id" value="<?= e($conversationId) ?>"><textarea id="aiQuestion" name="question" rows="2" maxlength="2000" placeholder="Ask about authorized <?= e(strtolower($assistants[$assistant][0] ?? 'ERP')) ?> data..." <?= !$aiSettings['enabled'] || !$aiSettings['configured'] ? 'disabled' : '' ?> required></textarea><button class="btn btn-danger" type="submit" <?= !$aiSettings['enabled'] || !$aiSettings['configured'] ? 'disabled' : '' ?>><i class="bi bi-arrow-up"></i><span class="visually-hidden">Send</span></button><small>Review AI advice before action. Sensitive secrets should never be entered here.</small></form>
    </section>
</div>

<section class="mt-4"><div class="d-flex align-items-end justify-content-between mb-3"><div><p class="eyebrow">Always available · deterministic rules</p><h2 class="h5 mb-0">Live Operational Insights</h2></div><span class="text-secondary small">Generated from ERP thresholds, not the AI model</span></div><div class="ai-insight-grid"><?php if (!$insights): ?><article class="card-panel ai-insight empty"><i class="bi bi-check2-circle"></i><strong>No active exceptions found</strong><span>Rule checks found no visible actionable exceptions.</span></article><?php endif; ?><?php foreach ($insights as $insight): ?><article class="card-panel ai-insight <?= e($insight['severity']) ?>"><div class="ai-insight-top"><span class="ai-insight-icon"><i class="bi <?= $insight['severity']==='critical'?'bi-exclamation-triangle':'bi-lightbulb' ?>"></i></span><span class="status-pill <?= e($insight['severity']==='critical'?'danger':'warning') ?>"><?= e(ucfirst($insight['severity'])) ?></span></div><h3><?= e($insight['title']) ?></h3><p><?= e($insight['summary']) ?></p><div class="ai-recommendation"><strong>Recommended review</strong><span><?= e($insight['recommended_action']) ?></span></div><form method="post" action="<?= e(url('ai.insight.status')) ?>"><?= Csrf::field() ?><input type="hidden" name="id" value="<?= e($insight['id']) ?>"><button class="btn btn-sm btn-outline-secondary" name="status" value="acknowledged">Acknowledge</button><button class="btn btn-sm btn-link text-secondary" name="status" value="dismissed">Dismiss</button></form></article><?php endforeach; ?></div></section>
