<section class="card-panel mx-auto" style="max-width:900px">
    <div class="d-flex justify-content-between border-bottom pb-3 mb-5"><div><p class="eyebrow">Human Resources</p><h2><?= e($record['company_name']) ?></h2><p><?= e($record['legal_name'] ?: $record['company_name']) ?> · GSTIN <?= e($record['tax_number'] ?: 'Not recorded') ?></p></div><img src="<?= e(asset('img/meatin-logo.png')) ?>" alt="Meatin" style="width:110px;height:70px;object-fit:contain"></div>
    <p class="text-end">Date: <?= e(date('d M Y',strtotime($record['issue_date']))) ?><br>Reference: <?= e($record['appointment_number']) ?></p>
    <p>To,<br><strong><?= e($record['full_name']) ?></strong> (<?= e($record['employee_number']) ?>)<br><?= nl2br(e($record['address'] ?: $record['alternate_address'] ?: 'Address on employee record')) ?></p>
    <h2 class="text-center my-5"><?= e(strtoupper(human_status($record['letter_type']))) ?> LETTER</h2>
    <p>Dear <?= e($record['full_name']) ?>,</p><p>We are pleased to confirm your <?= e(human_status($record['letter_type'])) ?> as <strong><?= e($record['designation']) ?></strong>, effective <?= e(date('d M Y',strtotime($record['effective_date']))) ?>. The recorded monthly salary / compensation basis is <strong><?= e(money($record['salary_amount'])) ?></strong>.</p>
    <div class="p-4 border rounded my-4"><h3>Terms and conditions</h3><p class="mb-0"><?= nl2br(e($record['terms'] ?: 'Employment is subject to company policy, applicable Indian labour requirements, confidentiality, hygiene, food-safety, attendance, and performance standards.')) ?></p></div>
    <p>Please sign and return a copy to acknowledge acceptance.</p><div class="row mt-5"><div class="col-6"><p><strong>For <?= e($record['company_name']) ?></strong><br><br><br>Authorized signatory<br><?= e($record['issued_by_name'] ?: 'Human Resources') ?></p></div><div class="col-6 text-end"><p><strong>Accepted by employee</strong><br><br><br><?= e($record['full_name']) ?><br>Date: __________________</p></div></div>
    <div class="text-end d-print-none"><button class="btn btn-danger" type="button" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print letter</button></div>
</section>
