<section class="card-panel mx-auto" style="max-width:900px">
    <div class="d-flex justify-content-between border-bottom pb-3 mb-4"><div><p class="eyebrow">Partner onboarding</p><h2>Welcome to <?= e($record['company_name']) ?></h2></div><img src="<?= e(asset('img/meatin-logo.png')) ?>" alt="Meatin" style="width:110px;height:70px;object-fit:contain"></div>
    <p><?= e(date('d M Y')) ?></p><h3>Dear <?= e($record['name']) ?>,</h3><p>We are pleased to confirm your registration as a <?= e(human_status($record['shareholder_type'])) ?> with unique partner ID <strong><?= e($record['shareholder_code']) ?></strong>. Your relationship is maintained through MeatinOS with controlled installment, share-change, dividend, receipt, and audit histories.</p>
    <div class="row g-3 my-4"><div class="col-md-4"><div class="p-3 border rounded"><small>Ownership</small><h3><?= e(number_format((float)$record['ownership_percent'],3)) ?>%</h3></div></div><div class="col-md-4"><div class="p-3 border rounded"><small>Share amount</small><h3><?= e(money($record['share_amount'])) ?></h3></div></div><div class="col-md-4"><div class="p-3 border rounded"><small>Pending amount</small><h3><?= e(money($record['pending_share_amount'])) ?></h3></div></div></div>
    <?php if($record['director_name']): ?><p><strong>Grouped under director:</strong> <?= e($record['director_name']) ?></p><?php endif; ?>
    <h3 class="mt-4">Registered nominees</h3><div class="table-responsive"><table class="table"><thead><tr><th>Name</th><th>Relationship</th><th>Allocation</th><th>Status</th></tr></thead><tbody><?php foreach($nominees as $nominee): ?><tr><td><?= e($nominee['nominee_name']) ?></td><td><?= e($nominee['relationship']) ?></td><td><?= e(number_format((float)$nominee['allocation_percent'],2)) ?>%</td><td><?= e(human_status($nominee['status'])) ?></td></tr><?php endforeach; ?><?php if(!$nominees): ?><tr><td colspan="4">No nominee has been registered.</td></tr><?php endif; ?></tbody></table></div>
    <p class="mt-4">We look forward to a transparent and successful association.</p><p><strong>For <?= e($record['legal_name'] ?: $record['company_name']) ?></strong><br>Authorized signatory</p>
    <div class="d-flex gap-2 justify-content-end d-print-none"><a class="btn btn-success" href="<?= e($whatsapp) ?>" target="_blank" rel="noopener noreferrer"><i class="bi bi-whatsapp me-1"></i>Send welcome message</a><button class="btn btn-danger" type="button" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print letter</button></div>
</section>
