<?php use MeatinOS\Core\Csrf; ?>
<div class="report-hero customer-portal-hero">
    <div><p class="eyebrow">Secure customer portal</p><h2>Welcome, <?= e($customer['name']) ?></h2><p>Follow orders, invoices, cold-chain dispatches, and proof of delivery in one place.</p></div>
    <div class="d-flex gap-2 flex-wrap"><a class="btn btn-light border" href="#complaintForm"><i class="bi bi-chat-left-text me-2"></i>Report an issue</a><a class="btn btn-danger" href="<?= e(url('module', ['name' => 'sales_orders'])) ?>"><i class="bi bi-box-arrow-up-right me-2"></i>View all orders</a></div>
</div>

<div class="row g-4 mt-1" id="complaintForm">
    <div class="col-xl-5"><article class="card-panel settings-card h-100"><div class="panel-heading"><div><h2>Submit a Complaint</h2><p>Send a quality, packaging, delivery, temperature, weight, or billing issue directly to the Quality team.</p></div><i class="bi bi-chat-left-text"></i></div><form method="post" action="<?= e(url('customer.complaint.create')) ?>" class="row g-3"><?= Csrf::field() ?><div class="col-12"><label class="form-label">Related order</label><select class="form-select" name="sales_order_id"><option value="">General / not linked to an order</option><?php foreach ($orders as $row): ?><option value="<?= e($row['id']) ?>"><?= e($row['order_number'].' - '.date('j M Y',strtotime((string)$row['order_date']))) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Category *</label><select class="form-select" name="category" required><option value="">Select...</option><option value="quality">Product quality</option><option value="temperature">Cold chain / temperature</option><option value="weight">Weight variance</option><option value="packaging">Packaging</option><option value="delivery">Delivery</option><option value="billing">Billing</option><option value="other">Other</option></select></div><div class="col-12"><label class="form-label">Complaint details *</label><textarea class="form-control" name="details" rows="5" minlength="10" maxlength="3000" required placeholder="Describe what happened, when it happened, and any affected items."></textarea></div><div class="col-12"><button class="btn btn-danger" type="submit"><i class="bi bi-send me-2"></i>Submit complaint</button></div></form></article></div>
    <div class="col-xl-7"><article class="card-panel table-panel h-100"><div class="workflow-section-title"><div><p class="eyebrow">Quality follow-up</p><h3>Complaint History</h3></div><span><?= e(number_format(count($complaints))) ?> recent</span></div><?php if (!$complaints): ?><div class="table-empty"><i class="bi bi-check2-circle"></i><strong>No complaints submitted</strong><span>Your submitted issues and their status will appear here.</span></div><?php else: ?><div class="table-responsive"><table class="table data-table align-middle"><thead><tr><th>Complaint</th><th>Date</th><th>Category</th><th>Details</th><th>Status</th></tr></thead><tbody><?php foreach ($complaints as $row): ?><tr><td><strong><?= e($row['complaint_number']) ?></strong></td><td><?= e(date('j M Y',strtotime((string)$row['complaint_date']))) ?></td><td><?= e(human_status((string)$row['category'])) ?></td><td><span class="complaint-detail"><?= e($row['details']) ?></span></td><td><span class="badge rounded-pill text-bg-<?= e(status_class((string)$row['status'])) ?>"><?= e(human_status((string)$row['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></article></div>
</div>

<div class="report-kpi-grid customer-kpi-grid">
    <div class="report-kpi"><span>Total orders</span><strong><?= e(number_format((float) $cards['total_orders'])) ?></strong><small>Account lifetime</small></div>
    <div class="report-kpi"><span>Open orders</span><strong><?= e(number_format((float) $cards['open_orders'])) ?></strong><small>Pending fulfillment</small></div>
    <div class="report-kpi"><span>Order value</span><strong><?= e(money($cards['order_value'])) ?></strong><small>Confirmed orders</small></div>
    <div class="report-kpi"><span>Outstanding</span><strong><?= e(money($cards['receivables'])) ?></strong><small><?= e($customer['payment_terms_days']) ?>-day payment terms</small></div>
</div>

<div class="row g-4 mt-1">
    <div class="col-xl-7"><article class="card-panel h-100"><div class="panel-heading"><div><h2>Orders & Invoices</h2><p>Commercial status for your account only</p></div></div><div class="table-responsive"><table class="table data-table mb-0"><thead><tr><th>Order</th><th>Order / delivery</th><th>Total</th><th>Invoice</th><th>Payment</th><th>Status</th></tr></thead><tbody><?php foreach ($orders as $row): ?><tr><td><strong><?= e($row['order_number']) ?></strong></td><td><?= e(date('j M Y', strtotime((string) $row['order_date']))) ?><small class="d-block text-secondary">Due <?= e(date('j M Y', strtotime((string) $row['delivery_date']))) ?></small></td><td><?= e(money($row['total_amount'])) ?></td><td><?= e($row['invoice_number'] ?: 'Pending') ?><small class="d-block text-secondary"><?= $row['invoice_number'] ? e(money($row['balance_amount'])) . ' outstanding' : '' ?></small></td><td><span class="badge rounded-pill text-bg-<?= e(status_class((string) $row['payment_status'])) ?>"><?= e(human_status((string) $row['payment_status'])) ?></span></td><td><span class="badge rounded-pill text-bg-<?= e(status_class((string) $row['status'])) ?>"><?= e(human_status((string) $row['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></article></div>
    <div class="col-xl-5"><article class="card-panel h-100"><div class="panel-heading"><div><h2>Delivery Tracking</h2><p>Reefer status and proof of delivery</p></div></div><div class="vehicle-list"><?php foreach ($dispatches as $row): ?><div class="vehicle-item"><span class="activity-icon bg-success-subtle text-success"><i class="bi bi-truck"></i></span><span><strong><?= e($row['dispatch_number']) ?></strong><small><?= e($row['order_number']) ?> &middot; <?= e($row['route_name']) ?></small><small><?= e($row['registration_number']) ?> &middot; <?= e(number_format((float) $row['temperature_c'], 1)) ?>&deg;C &middot; POD <?= e($row['pod_reference'] ?: 'pending') ?></small></span><span class="badge rounded-pill text-bg-<?= e(status_class((string) $row['status'])) ?>"><?= e(human_status((string) $row['status'])) ?></span></div><?php endforeach; ?><?php if (!$dispatches): ?><div class="table-empty"><i class="bi bi-truck"></i><strong>No dispatches yet</strong><span>Approved deliveries will appear here.</span></div><?php endif; ?></div></article></div>
</div>
