<div class="trace-hero card-panel">
    <div><p class="eyebrow">Farm to customer</p><h2>End-to-End Traceability</h2><p>Enter any receiving batch, production batch, inventory lot, sales order, invoice, or dispatch number.</p></div>
    <form method="get" class="trace-search"><input type="hidden" name="route" value="traceability"><i class="bi bi-upc-scan"></i><input class="form-control form-control-lg" type="search" name="q" value="<?= e($query) ?>" placeholder="Example: PB-260806-01" required><button class="btn btn-danger btn-lg" type="submit">Trace</button></form>
</div>

<?php if ($query !== '' && !$chain): ?>
    <div class="empty-state card-panel"><div class="empty-icon"><i class="bi bi-search"></i></div><h2>No traceability chain found</h2><p>Check the number and try again. Search is exact to prevent ambiguous lot identification.</p></div>
<?php elseif ($chain): $head = $chain[0]; ?>
    <div class="trace-summary"><div><span>Production batch</span><strong><?= e($head['production_batch']) ?></strong></div><div><span>Supplier / farm</span><strong><?= e($head['supplier_name']) ?></strong><small><?= e($head['farm_name']) ?></small></div><div><span>Yield</span><strong><?= e(number_format((float) $head['yield_percent'], 2)) ?>%</strong><small><?= e(number_format((float) $head['output_weight_kg'])) ?> kg output</small></div><div><span>Current status</span><strong class="text-<?= e(status_class((string) $head['production_status'])) ?>"><?= e(human_status((string) $head['production_status'])) ?></strong><small><?= e(human_status((string) $head['stage'])) ?></small></div></div>
    <div class="trace-flow">
        <article><div class="trace-icon"><i class="bi bi-clipboard2-pulse"></i></div><span>1 &middot; Receiving</span><h3><?= e($head['receiving_batch']) ?></h3><p><?= e(number_format((float) $head['bird_count'])) ?> birds &middot; <?= e(number_format((float) $head['mortality_count'])) ?> mortality</p><span class="badge rounded-pill text-bg-<?= e(status_class((string) $head['vet_status'])) ?>">Vet <?= e(human_status((string) $head['vet_status'])) ?></span></article>
        <i class="bi bi-arrow-right"></i>
        <article><div class="trace-icon"><i class="bi bi-diagram-3"></i></div><span>2 &middot; Production</span><h3><?= e($head['production_batch']) ?></h3><p><?= e(number_format((float) $head['input_weight_kg'])) ?> kg in &middot; <?= e(number_format((float) $head['output_weight_kg'])) ?> kg out</p><span class="badge rounded-pill text-bg-<?= e(status_class((string) $head['production_status'])) ?>"><?= e(human_status((string) $head['production_status'])) ?></span></article>
        <i class="bi bi-arrow-right"></i>
        <article><div class="trace-icon"><i class="bi bi-shield-check"></i></div><span>3 &middot; Quality</span><h3><?= e($head['check_number'] ?: 'Pending check') ?></h3><p><?= $head['grade'] ? 'Grade ' . e($head['grade']) : 'No grade recorded' ?> &middot; <?= $head['checked_at'] ? e(date('j M, g:i A', strtotime((string) $head['checked_at']))) : '&mdash;' ?></p><span class="badge rounded-pill text-bg-<?= e(status_class((string) ($head['quality_status'] ?? 'pending'))) ?>"><?= e(human_status((string) ($head['quality_status'] ?? 'pending'))) ?></span></article>
    </div>
    <article class="card-panel mt-4">
        <div class="panel-heading"><div><h2>Lots, customers & delivery</h2><p>All downstream allocations connected to this production batch</p></div></div>
        <div class="table-responsive"><table class="table data-table mb-0"><thead><tr><th>Inventory lot</th><th>Product / storage</th><th>Expiry</th><th>Sales order / customer</th><th>Invoice</th><th>Dispatch / vehicle</th><th>Status / POD</th></tr></thead><tbody><?php foreach ($chain as $row): ?><tr><td><strong><?= e($row['lot_number'] ?: '-') ?></strong></td><td><?= e($row['product_name'] ?: '-') ?><small class="d-block text-secondary"><?= e($row['storage_zone'] ?: '-') ?></small></td><td><?= $row['expiry_date'] ? e(date('j M Y', strtotime((string) $row['expiry_date']))) : '&mdash;' ?></td><td><?= e($row['order_number'] ?: 'Unallocated') ?><small class="d-block text-secondary"><?= e($row['customer_name'] ?: '-') ?></small></td><td><?= e($row['invoice_number'] ?: '-') ?></td><td><?= e($row['dispatch_number'] ?: '-') ?><small class="d-block text-secondary"><?= e($row['registration_number'] ?: '-') ?></small></td><td><span class="badge rounded-pill text-bg-<?= e(status_class((string) ($row['dispatch_status'] ?? 'pending'))) ?>"><?= e(human_status((string) ($row['dispatch_status'] ?? 'pending'))) ?></span><small class="d-block text-secondary mt-1">POD: <?= e($row['pod_reference'] ?: 'Pending') ?></small></td></tr><?php endforeach; ?></tbody></table></div>
    </article>
<?php endif; ?>
